services:
  db:
    image: postgis/postgis:14-3.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: crop_risk_db
    command: ["-c", "max_connections=200"]
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/docker/db-init:/docker-entrypoint-initdb.d:ro

  web:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/crop_risk_db
      - REDIS_URL=redis
    volumes:
      - ./backend:/app:cached
      - ./data:/app/data:cached
      - ./logs:/app/logs:cached
      - ./ml:/app/ml:cached
      - ./data/earthengine:/root/.config/earthengine:cached

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  worker:
    build: ./backend
    command: celery -A app.tasks.celery_app.celery_app worker --loglevel=info --concurrency=6
    env_file: .env
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/app:cached
      - ./data:/app/data:cached
      - ./logs:/app/logs:cached
      - ./ml:/app/ml:cached
      - ./data/earthengine:/root/.config/earthengine:cached
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis
      - DATABASE_URL=postgresql://postgres:1234@db:5432/crop_risk_db

  beat:
    build: ./backend
    command: celery -A app.tasks.celery_app.celery_app beat --loglevel=info
    env_file: .env
    depends_on:
      - redis
      - db
    volumes:
      - ./backend:/app:cached
      - ./data:/app/data:cached
      - ./logs:/app/logs:cached
      - ./ml:/app/ml:cached
      - ./data/earthengine:/root/.config/earthengine:cached
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis
      - DATABASE_URL=postgresql://postgres:1234@db:5432/crop_risk_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  db_data:
